import * as XLSX from 'xlsx';
import { ReportData, SBIInvoice, AgeAnalysisClaim } from './types';
import { normalizeRO } from './parsePDF';

export function generateWeeklyReport(data: ReportData): ArrayBuffer {
  const wb = XLSX.utils.book_new();
  createWIPSheet(wb, data);
  createAgeAnalysisSheet(wb, data);
  createDmsSheet(wb, data);
  createPartsReturnSheet(wb);
  createPlaceholderSheet(wb, 'DAS', ['Snip of DAS']);
  createScrapListSheet(wb);
  createTrainingSheet(wb);
  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}

function createWIPSheet(wb: XLSX.WorkBook, data: ReportData) {
  const rows: any[][] = [
    ['WARRANTY WIP extract should be dumped directly from DMS. No changes may be made except for additional comments column added.'],
    ['If I open the WIP, I need to know exactly what is happening on each Warranty job card (VOP, parts back order etc)'],
    ['BSI Overview screen showing TOTAL JOBS on the overview as well as BSI Invoicing screen showing outstanding WAR invoicing snaps to be added below the WIP'],
    [], [], [], [], [], [],
    ['Service WIP Ageing Report'],
    ['Company:', 'MMG Ford Harrismith (M026)', '', '', '', '', '', 'Run By:'],
    ['From Date:', '', '', '', '', '', '', 'Run Date & Time:'],
    ['To Date:'], ['Booking:', 'no'], ['Estimate:', 'no'],
    ['Work in Progress:', 'yes'], ['Delete:', 'no'],
    ['Selected Companies List:', 'M026'], [],
    ['RO Number', 'Service Advisor', 'Date Created', 'Customer Name', 'Invoice To', 'Job Status', 'Job Type', 'VIN Number', 'Engine Number', 'Registration Number', 'Days Outstanding', 'Comments'],
  ];
  for (const e of data.wipEntries) {
    rows.push([e.roNumber, e.serviceAdvisor, e.dateCreated, e.customerName, e.invoiceTo, e.jobStatus, e.jobType, e.vinNumber, e.engineNumber, e.registrationNumber, e.daysOutstanding, e.comment]);
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 12 }, { wch: 20 }, { wch: 12 }, { wch: 30 }, { wch: 28 }, { wch: 10 }, { wch: 8 }, { wch: 20 }, { wch: 15 }, { wch: 18 }, { wch: 16 }, { wch: 80 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Warranty WIP');
}

function createAgeAnalysisSheet(wb: XLSX.WorkBook, data: ReportData) {
  const rows: any[][] = [
    ['AGE ANALYSIS extract should be dumped directly from DMS. No changes may be made except for additional comments column added.'],
    ['Columns added for status (Paid, paid adj, denied, DAR, cancelled). On Paid / Paid adj status - add amounts, date and SB numbers'],
    ['On Paid adj, denied, DAR, cancelled status - please explain reason why as well as action plan.'],
    [], [], [], [], [], [],
    ['Claim No', 'Ro Number', 'Job Type', 'Account No', 'Invoice No', 'Invoice Date', 'Days 0 To 30', 'Days 31 To 60', 'Days 61 To 90', 'Days 91 To 120', 'Days 121 To 150', 'Days 150', 'Total', 'Total PD', 'Diff', 'Comments'],
    [], [], [], [], [],
    ['Mortimer Motors (Pty) Ltd'], ['MMG Ford Harrismith'], ['Warranty Age Analysis'],
    ['Company: M026'], ['Claim Status: ALL'], ['Claim No: ALL'], ['Ro Number: ALL'],
    [`Generated On: ${data.generatedOn}`], [`Generated By: ${data.generatedBy}`], [],
    ['Claim No', 'Ro Number', 'Vin Number', 'Job Type', 'Account No', 'Invoice No', 'Invoice Date', 'Days 0 To 30', 'Days 31 To 60', 'Days 61 To 90', 'Days 91 To 120', 'Days 121 To 150', 'Days 150', 'Total', 'Total PD', 'Diff', 'Comments'],
  ];
  let grandTotal = 0, grandPD = 0, grandDiff = 0;
  for (const c of data.ageAnalysisClaims) {
    grandTotal += c.total; grandPD += c.totalPD || 0; grandDiff += c.diff || 0;
    rows.push([c.claimNo, c.roNumber, c.vinNumber, c.jobType, c.accountNo, c.invoiceNo, c.invoiceDate, c.days0to30, c.days31to60, c.days61to90, c.days91to120, c.days121to150, c.days150plus, c.total, c.totalPD ?? '', c.diff ?? '', c.comment]);
  }
  rows.push(['Grand Total', '', '', '', '', '', '', '', '', '', '', '', '', grandTotal, grandPD, grandDiff, '']);
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 14 }, { wch: 12 }, { wch: 20 }, { wch: 8 }, { wch: 12 }, { wch: 16 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 14 }, { wch: 14 }, { wch: 10 }, { wch: 12 }, { wch: 12 }, { wch: 10 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Age Analysis');
}

function createPlaceholderSheet(wb: XLSX.WorkBook, name: string, instructions: string[]) {
  const ws = XLSX.utils.aoa_to_sheet(instructions.map(i => [i]));
  ws['!cols'] = [{ wch: 120 }];
  XLSX.utils.book_append_sheet(wb, ws, name);
}

function createDmsSheet(wb: XLSX.WorkBook, data: ReportData) {
  const header: string[][] = [
    ['Screenshot to be taken directly from DMS showing totals on Age - do not crop out date and time in the right bottom corner'],
    ['NOTE THAT DMS TOTAL SHOULD MATCH THAT OF YOUR EXCEL RECONCILIATION TOTAL.'],
    ['If no access to Age on DMS - Age should be supplied in PDF and added below.'],
    [],
  ];
  const rows: any[][] = [...header];
  if (data.dmsRawLines && data.dmsRawLines.length) {
    rows.push(['--- DMS Raw Data Dump ---']);
    rows.push([]);
    for (const r of data.dmsRawLines) rows.push(r);
  }
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = Array(20).fill({ wch: 18 });
  XLSX.utils.book_append_sheet(wb, ws, 'DMS Screenshot');
}

function createPartsReturnSheet(wb: XLSX.WorkBook) {
  const ws = XLSX.utils.aoa_to_sheet([
    ['Parts return to be dumped from OWS as per below example'],
    ['Tag printed status and Debit warning status to be dumped and included below'],
    ['RETURN PART STATUS:'], ['TAGS PRINTED STATUS:'], ['PRINT TAG'], ['DEBT WARNING'], ['Part Shipped'], ['DEBIT WARNING STATUS:'],
  ]);
  ws['!cols'] = [{ wch: 80 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Parts Return');
}

function createScrapListSheet(wb: XLSX.WorkBook) {
  const ws = XLSX.utils.aoa_to_sheet([
    ['SCRAP LIST ALONG WITH SNAP OF LETTER / CERTIFICATE AND PHOTOS OF DESTROYED PARTS'],
    ['THIS REMAINS ON THE REPORT UNTIL THE NEXT SCRAPPING - DO NOT UPDATE TO A BLANK SHEET!'],
  ]);
  ws['!cols'] = [{ wch: 100 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Scrap List');
}

function createTrainingSheet(wb: XLSX.WorkBook) {
  const rows: any[][] = [
    ['', 'Last update:', '2025/08/01 - Required by MSXI', '', '', '', '', '', '', 'Required by Ford'],
    ['', 'COURSE CODE', 'COURSE NAME', 'PLATFORM', 'Completed', 'Score', '', '', 'Southern Africa Global Warranty Training Course List'],
    ['BASIC'],
    ['1', 'FMCSA3645W', 'One Warranty Solution: Introduction', 'STARS'],
    ['2', 'FMCSA3646W', 'One Warranty Solution: Claim Entry and Processing', 'STARS'],
    ['3', 'FMCSA3647W', 'One Warranty Solution: Prior Approval', 'STARS'],
    ['4', 'FMCSA3648W', 'One Warranty Solution: Parts Return', 'STARS'],
    ['5', 'NTW6713AP0', 'Warranty Administrator Fundamentals', 'STARS'],
    ['6', 'NTW6718AP0', 'Repair Order Warranty Essentials OWS', 'STARS / Wingspan'],
    ['7', 'NTW6720SA0', 'Warranty Basics', 'Wingspan'],
    ['8', 'NTW6722SA0', 'Warranty Information', 'Wingspan'],
    ['ADVANCED'],
    ['9', 'F401102103', 'FDRS Ford Diagnostic and Repair System and IDS Functions', 'STARS'],
    ['10', '34S16W0', 'Understanding Electronic Systems', 'STARS'],
  ];
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = [{ wch: 6 }, { wch: 16 }, { wch: 60 }, { wch: 18 }, { wch: 12 }, { wch: 8 }, { wch: 4 }, { wch: 4 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Training');
}

export function generateSBPayments(sbiInvoices: SBIInvoice[], claims: AgeAnalysisClaim[]): ArrayBuffer {
  const wb = XLSX.utils.book_new();
  const roToInvoice = new Map<string, string>();
  for (const c of claims) {
    const norm = normalizeRO(c.roNumber);
    if (c.invoiceNo) roToInvoice.set(norm, c.invoiceNo);
  }

  for (const sbi of sbiInvoices) {
    const rows: any[][] = [
      ['(SBI) SELF BILLING TAX INVOICE'], [],
      ['GEOGRAPHICAL SALES AREA:', 'ZAF', '', '', 'DATE OF ISSUE:', sbi.dateOfIssue],
      ['CURRENCY:', 'ZAR', '', '', 'INVOICE NUMBER:', `91106-${sbi.invoiceNumber}`],
      [], ['SUPPLIER', '', '', '', 'CUSTOMER'],
      ['Mortimer Motors (Pty) Ltd', '', '', '', 'FORD MOTOR CO. OF SOUTHERN AFRICA'],
      [], [],
      ['SERVICES PERFORMED BY THE DEALER IN CONNECTION WITH WARRANTY REPAIRS'], [],
      ['REPAIR ORDER NO.', 'Claim Type', 'Sub Code', 'VIN', 'DATE OF REPAIR', 'NET AMOUNT', 'VAT RATE %', 'VAT AMOUNT', 'TOTAL (INCLUDING VAT)', 'INVOICE NO.'],
    ];
    let totalNet = 0, totalVat = 0, totalInc = 0;
    for (const sc of sbi.claims) {
      const normRO = normalizeRO(sc.repairOrderNo);
      totalNet += sc.netAmount; totalVat += sc.vatAmount; totalInc += sc.totalIncVAT;
      rows.push([sc.repairOrderNo, sc.claimType, sc.subCode, sc.vin, sc.dateOfRepair, sc.netAmount, sc.vatRate, sc.vatAmount, sc.totalIncVAT, roToInvoice.get(normRO) || '']);
    }
    rows.push([], ['TOTAL', '', '', '', '', totalNet, '', totalVat, totalInc, '']);
    rows.push([], ['GRAND TOTAL', '', '', '', '', '', '', '', sbi.grandTotal || totalInc]);
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 20 }, { wch: 12 }, { wch: 10 }, { wch: 20 }, { wch: 16 }, { wch: 14 }, { wch: 12 }, { wch: 14 }, { wch: 20 }, { wch: 16 }];
    XLSX.utils.book_append_sheet(wb, ws, (sbi.invoiceNumber || 'SBI').substring(0, 31));
  }
  return XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
}
