import * as XLSX from 'xlsx';
import { AgeAnalysisClaim, WIPEntry } from './types';

export function parseAgeAnalysisExcel(file: ArrayBuffer): {
  claims: AgeAnalysisClaim[];
  generatedOn: string;
  generatedBy: string;
} {
  const workbook = XLSX.read(file, { type: 'array' });
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const rows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' });

  let generatedOn = '';
  let generatedBy = '';
  const claims: AgeAnalysisClaim[] = [];
  let headerRowIndex = -1;

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const firstCell = String(row[0] || '').trim();
    if (firstCell.startsWith('Generated On:')) generatedOn = firstCell.replace('Generated On:', '').trim();
    if (firstCell.startsWith('Generated By:')) generatedBy = firstCell.replace('Generated By:', '').trim();
    if (firstCell === 'Claim Status' && String(row[1] || '').trim() === 'Claim No') headerRowIndex = i;
  }

  if (headerRowIndex === -1) return { claims, generatedOn, generatedBy };

  for (let i = headerRowIndex + 1; i < rows.length; i++) {
    const row = rows[i];
    const claimStatus = String(row[0] || '').trim();
    if (!claimStatus || claimStatus === 'Grand Total') {
      if (claimStatus === 'Grand Total') break;
      continue;
    }
    claims.push({
      claimStatus,
      claimNo: String(row[1] || '').trim(),
      roNumber: String(row[2] || '').trim(),
      vinNumber: String(row[3] || '').trim(),
      jobType: String(row[4] || '').trim(),
      accountNo: String(row[5] || '').trim(),
      invoiceNo: String(row[6] || '').trim(),
      invoiceDate: formatDate(row[7]),
      days0to30: parseFloat(row[8]) || 0,
      days31to60: parseFloat(row[9]) || 0,
      days61to90: parseFloat(row[10]) || 0,
      days91to120: parseFloat(row[11]) || 0,
      days121to150: parseFloat(row[12]) || 0,
      days150plus: parseFloat(row[13]) || 0,
      total: parseFloat(row[14]) || 0,
      totalPD: null,
      diff: null,
      comment: '',
      matched: false,
      matchedSBI: '',
    });
  }

  return { claims, generatedOn, generatedBy };
}

export function parseWIPExcel(file: ArrayBuffer): WIPEntry[] {
  const workbook = XLSX.read(file, { type: 'array' });
  const sheet = workbook.Sheets[workbook.SheetNames[0]];
  const rows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' });

  const entries: WIPEntry[] = [];
  let headerRowIndex = -1;

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    if (String(row[0] || '').trim() === 'Co Number' && String(row[1] || '').trim() === 'RO Number') {
      headerRowIndex = i;
      break;
    }
  }

  if (headerRowIndex === -1) return entries;

  for (let i = headerRowIndex + 1; i < rows.length; i++) {
    const row = rows[i];
    const roNumber = String(row[1] || '').trim();
    if (!roNumber) continue;
    const customerStates = String(row[50] || '').trim();
    const saComments = String(row[51] || '').trim();
    entries.push({
      roNumber,
      serviceAdvisor: String(row[2] || '').trim(),
      dateCreated: formatDate(row[3]),
      customerName: String(row[4] || '').trim(),
      invoiceTo: String(row[5] || '').trim(),
      jobStatus: String(row[6] || '').trim(),
      jobType: String(row[7] || '').trim(),
      vinNumber: String(row[8] || '').trim(),
      engineNumber: String(row[11] || '').trim(),
      registrationNumber: String(row[12] || '').trim(),
      daysOutstanding: parseInt(row[14]) || 0,
      comment: [customerStates, saComments].filter(Boolean).join(' | '),
    });
  }

  const seen = new Set<string>();
  return entries.filter(e => {
    const key = e.roNumber + '|' + e.dateCreated;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function formatDate(value: any): string {
  if (!value) return '';
  if (typeof value === 'number') {
    const date = XLSX.SSF.parse_date_code(value);
    if (date) return `${date.m}/${date.d}/${String(date.y).slice(-2)}`;
  }
  return String(value).trim();
}
